#define txt_name 0
#define txt_size 1
#define txt_hello 2
#define txt_station 3
#define txt_print 4
#define txt_history 5
#define txt_quit 6
#define txt_temp 7
#define txt_wind 8
#define txt_dir 9
#define txt_caps 10
#define txt_compass 11
#define txt_the 12
#define txt_weather 13
#define txt_degrees 14
#define txt_mph 15
#define txt_N 16
#define txt_NE 17
#define txt_E 18
#define txt_SE 19
#define txt_S 20
#define txt_SW 21
#define txt_W 22
#define txt_NW 23
#define txt_wHistory 24
#define txt_err1 25
#define txt_err2 26
#define txt_err3 27
#define txt_invalid 28
#define txt_main 29
#define txt_manager 30
#define txt_create 31
#define txt_select 32
#define txt_print2 33
#define txt_quit2 34
#define txt_nothing 35
#define txt_input2 36


